version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READ_PACKAGES_TOKEN}}
  npm-fontawesome:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: ${{secrets.FONT_AWESOME_TOKEN}}
updates:
  - package-ecosystem: "npm"
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
      - dependency-name: "electron"
      - dependency-name: "electron-builder"
      - dependency-name: "tailwindcss"
      - dependency-name: "prettier"
      - dependency-name: "typescript"
    ignore:
      - dependency-name: "electron"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-minor"]
        # There are problems with v4 and pure ESM module
      - dependency-name: "p-limit"
        update-types: ["version-update:semver-major"]
      - dependency-name: "p-queue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "lowdb"
        update-types: ["version-update:semver-major"]
        # There seem to be larger changes, maybe work on it later.
      - dependency-name: "*react-router*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@fortawesome*"
        update-types: ["version-update:semver-major"]
