version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
      - dependency-name: "electron"
      - dependency-name: "electron-builder"
      - dependency-name: "tailwindcss"
      - dependency-name: "prettier"
      - dependency-name: "typescript"
    ignore:
      - dependency-name: "electron"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-minor"]
        # There are problems with v4 and pure ESM module
      - dependency-name: "p-limit"
        update-types: ["version-update:semver-major"]
