name: Delete old releases

on:
  workflow_dispatch:
  schedule:
    - cron: "13 12 * * 6"

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install Node and NPM
        uses: actions/setup-node@v2g
        with:
          node-version: 16
          cache: npm

      - name: Setup NPM auth token for font awesome pro & github packages
        run: >
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" >> ~/.npmrc &&
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: cat ~/.npmrc && npm ci --ignore-scripts --verbose

      - name: Delete objects from S3
        env:
          ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npm run delete-old-releases

      - name: Archive npm logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs-test
          path: ~/.npm/_logs
