name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    # macOS code signing only works on macOS
    # runs-on: macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      # add a specially install private packages on
      - name: setup github secret token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}" >> .npmrc

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          # FIXME
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

          # Required when pushing releases to GitHub
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Push to S3-compliant Object Storag
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          yarn cross-env SENTRY_DSN=${{ secrets.SENTRY_DSN }} UPDATE_FEED_URL=${{ secrets.UPDATE_FEED_URL }} yarn build &&
          yarn electron-builder --publish always --win --mac --linux
