name: Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup NPM auth token for font awesome pro & github packages
        run: >
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" >> .npmrc &&
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build package and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm test
