name: Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Setup NPM auth token for font awesome pro & github packages
        shell: bash
        run: >
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" >> ~/.npmrc &&
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: cat ~/.npmrc && npm ci --ignore-scripts --verbose

      - name: Setup dotenv files
        shell: bash
        run: >
          echo $GITHUB_TAG_VERSION &&
          if [[ $GITHUB_TAG_VERSION == *"beta"* || $GITHUB_TAG_VERSION == *"alpha"* ]]; then
          echo "PLATFORM_URL=${{ secrets.BETA_PLATFORM_URL }}" >> .env && echo "SERIOUS_PROTECTION=${{ secrets.BETA_SERIOUS_PROTECTION }}" >> .env;
          else echo "PLATFORM_URL=${{ secrets.PLATFORM_URL }}" >> .env && echo "SERIOUS_PROTECTION=${{ secrets.SERIOUS_PROTECTION }}" >> .env; fi &&
          echo "TRACK_EVENTS=${{ secrets.TRACK_EVENTS }}" >> .env &&
          if [[ $GITHUB_TAG_VERSION == *"alpha"* ]]; then echo "UPDATE_FEED_URL=${{ secrets.INTERNAL_UPDATE_FEED_URL }}" >> .env; else echo "UPDATE_FEED_URL=${{ secrets.UPDATE_FEED_URL }}" >> .env; fi &&
          if [[ $GITHUB_TAG_VERSION == *"beta"* || $GITHUB_TAG_VERSION == *"alpha"* ]]; then echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env; else echo "SENTRY_DSN=" >> .env; fi

      - name: Install Playwright
        run: npx playwright install

      - name: Build package and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm test

      - name: Archive npm logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs-test
          path: ~/.npm/_logs

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
