name: Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Setup NPM auth token for font awesome pro & github packages
        shell: bash
        run: >
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc &&
          echo "@algorithmwatch:registry=https://npm.pkg.github.com/" >> ~/.npmrc &&
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> ~/.npmrc &&
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" >> ~/.npmrc &&
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        continue-on-error: true
        run: npm ci --ignore-scripts --verbose

      # hotfix: retry installation
      - name: Install dependencies
        continue-on-error: true
        run: npm ci --ignore-scripts --verbose

      - name: Build package and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm test

      # if any previous step has failed, get the npm logs
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
